//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char iMask2 [] = {
4, 16,
0xFF, 0x55, 0xAB, 0xFF, 0xFF, 0xD5, 0xAA, 0xFF, 
};
