//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char iMask1 [] = {
BITMAP_TYPE_1BPP_VERTICAL,
16, 4,
0x0F, 0x0D, 0x0B, 0x0D, 0x0B, 0x0B, 0x0B, 0x0D, 0x0B, 0x0D, 0x0B, 0x0B, 0x0B, 0x0D, 0x0B, 0x0F
};

const unsigned char iMask2 [] = {
BITMAP_TYPE_1BPP_VERTICAL,
4, 16,
0xFF, 0x55, 0xAB, 0xFF, 0xFF, 0xD5, 0xAA, 0xFF,
};
