//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char jMask2 [] = {
8, 12,
0xFF, 0xAB, 0x55, 0xFB, 0x0D, 0x0B, 0x0D, 0x0F, 0x0F, 0x0A, 0x0D, 0x0F, 
};
