//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char lMask3 [] = {
12,8,
0xFF, 0xAB, 0xD5, 0xFB, 0x0D, 0x0B, 0x0D, 0x0B, 0x0D, 0x0B, 0x0D, 0x0F, 
};
