//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char lMask4 [] = {
8, 12,
0x0F, 0x0D, 0x0B, 0x0D, 0xFB, 0x55, 0xAB, 0xFF, 0x00, 0x00, 0x00, 0x00, 
};
