//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char oMask1 [] = {
BITMAP_TYPE_1BPP_VERTICAL,
8, 8,
0xFF, 0xD5, 0xAB, 0xD5, 0xAB, 0xD5, 0xAB, 0xFF, 
};
