//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char sMask1 [] = {
BITMAP_TYPE_1BPP_VERTICAL,
12, 8,
0xF0, 0xB0, 0xD0, 0xB0, 0xDF, 0xAB, 0xD5, 0xFB, 0x0D, 0x0B, 0x0D, 0x0F, 
};

const unsigned char sMask2 [] = {
BITMAP_TYPE_1BPP_VERTICAL,
8, 12,
0xFF, 0xD5, 0xAB, 0xDF, 0xB0, 0x50, 0xB0, 0xF0, 0x00, 0x00, 0x00, 0x00,
};
