//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char sMask2 [] = {
8, 12,
0xFF, 0xD5, 0xAB, 0xDF, 0xB0, 0x50, 0xB0, 0xF0, 0x00, 0x00, 0x00, 0x00, 
};
