//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char tMask3 [] = {
12, 8,
0x0F, 0x0D, 0x0B, 0x0D, 0xFB, 0xD5, 0xAB, 0xFD, 0x0B, 0x0D, 0x0B, 0x0F, 
};
