//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char tMask4 [] = {
8, 12,
0xF0, 0xB0, 0xD0, 0xB0, 0xDF, 0xAB, 0x55, 0xFF, 0x00, 0x00, 0x00, 0x00, 
};
