//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char tMask2 [] = {
8, 12,
0xFF, 0xAB, 0x55, 0xBF, 0xD0, 0xB0, 0xD0, 0xF0, 0x0F, 0x0A, 0x0D, 0x0F, 
};
