//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char zMask1 [] = {
BITMAP_TYPE_1BPP_VERTICAL,
12, 8,
0x0F, 0x0D, 0x0B, 0x0D, 0xFB, 0xD5, 0xAB, 0xDF, 0xB0, 0xD0, 0xB0, 0xF0, 
};

const unsigned char zMask2 [] = {
BITMAP_TYPE_1BPP_VERTICAL,
8, 12,
0xF0, 0xB0, 0x50, 0xB0, 0xDF, 0xAB, 0xD5, 0xFF, 0x0F, 0x0A, 0x0D, 0x0F,
};
