//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char zMask2 [] = {
BITMAP_TYPE_1BPP_VERTICAL,
8, 12,
0xF0, 0xB0, 0x50, 0xB0, 0xDF, 0xAB, 0xD5, 0xFF, 0x0F, 0x0A, 0x0D, 0x0F, 
};
